services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    container_name: auth-service
    ports:
      - '3001:3001'
    # .env 파일은 Dockerfile에서 COPY되므로 이곳에 따로 environment 지정 불필요
    depends_on:
      - mongodb

  event:
    build:
      context: .
      dockerfile: apps/event/Dockerfile
    container_name: event-service
    ports:
      - '3002:3002'
    depends_on:
      - mongodb

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    container_name: gateway
    ports:
      - '3000:3000'
    depends_on:
      - auth
      - event

volumes:
  mongo-data:
